//! Pre-generated protobuf code for MCP gRPC transport.
//!
//! This file contains the Rust code generated from `proto/mcp.proto` using prost/tonic.
//! It is checked into the repository to avoid requiring protoc at build time, which
//! enables builds on all platforms including Windows where protobuf-src has known
//! linker issues with MSVC.
//!
//! ## Regenerating This File
//!
//! If you modify `proto/mcp.proto`, regenerate this file using:
//!
//! ```bash
//! just generate-proto
//! ```
//!
//! Or manually:
//!
//! ```bash
//! cargo build -p mcpkit-transport --features grpc,regenerate-proto
//! cp target/debug/build/mcpkit-transport-*/out/mcp.rs \
//!    crates/mcpkit-transport/src/grpc/mcp_proto.rs
//! ```
//!
//! Then add this header comment back to the file.

// ============================================================================
// BEGIN GENERATED CODE - DO NOT EDIT BELOW THIS LINE
// Generated by prost-build from proto/mcp.proto
// ============================================================================

// Allow clippy lints that are triggered by generated code
#![allow(clippy::default_trait_access)]

// This file is @generated by prost-build.
/// MCP message envelope for gRPC transport.
///
/// The payload contains the JSON-RPC message as a string. This approach
/// allows the gRPC layer to handle transport concerns while the MCP layer
/// handles protocol semantics.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpMessage {
    /// The JSON-RPC message payload as a string.
    /// Contains the serialized MCP protocol message (request, response, or notification).
    #[prost(string, tag = "1")]
    pub payload: ::prost::alloc::string::String,
    /// Optional metadata key-value pairs.
    /// Can be used for transport-level metadata like session IDs, tracing info, etc.
    #[prost(map = "string, string", tag = "2")]
    pub metadata:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// Generated client implementations.
pub mod mcp_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// MCP gRPC service for bidirectional streaming communication.
    ///
    /// This service provides a single bidirectional streaming RPC that allows
    /// both client and server to send MCP messages at any time. This enables:
    /// - Request/response patterns (client sends request, server responds)
    /// - Server-initiated notifications
    /// - Full-duplex communication
    #[derive(Debug, Clone)]
    pub struct McpServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl McpServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> McpServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> McpServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::BoxBody>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            McpServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bidirectional streaming RPC for MCP communication.
        ///
        /// Both client and server can send McpMessage instances at any time.
        /// The streams operate independently, allowing for flexible communication
        /// patterns including request/response, notifications, and progress updates.
        pub async fn stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::McpMessage>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::McpMessage>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/mcp.McpService/Stream");
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mcp.McpService", "Stream"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod mcp_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with McpServiceServer.
    #[async_trait]
    pub trait McpService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Stream method.
        type StreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::McpMessage, tonic::Status>,
            > + std::marker::Send
            + 'static;
        /// Bidirectional streaming RPC for MCP communication.
        ///
        /// Both client and server can send McpMessage instances at any time.
        /// The streams operate independently, allowing for flexible communication
        /// patterns including request/response, notifications, and progress updates.
        async fn stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::McpMessage>>,
        ) -> std::result::Result<tonic::Response<Self::StreamStream>, tonic::Status>;
    }
    /// MCP gRPC service for bidirectional streaming communication.
    ///
    /// This service provides a single bidirectional streaming RPC that allows
    /// both client and server to send MCP messages at any time. This enables:
    /// - Request/response patterns (client sends request, server responds)
    /// - Server-initiated notifications
    /// - Full-duplex communication
    #[derive(Debug)]
    pub struct McpServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> McpServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for McpServiceServer<T>
    where
        T: McpService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/mcp.McpService/Stream" => {
                    #[allow(non_camel_case_types)]
                    struct StreamSvc<T: McpService>(pub Arc<T>);
                    impl<T: McpService> tonic::server::StreamingService<super::McpMessage> for StreamSvc<T> {
                        type Response = super::McpMessage;
                        type ResponseStream = T::StreamStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::McpMessage>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as McpService>::stream(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(empty_body());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for McpServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "mcp.McpService";
    impl<T> tonic::server::NamedService for McpServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}

// ============================================================================
// END GENERATED CODE
// ============================================================================
